name: ML Workflow CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12 with Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.12
          environment-file: MLProject/conda.yaml
          activate-environment: ml-env
          auto-update-conda: true
          use-mamba: true

      - name: Install additional dependencies
        run: |
          pip install --upgrade pip
          pip install mlflow dagshub tqdm scikit-learn pandas

      - name: Set MLflow Tracking URI to SQLite
        run: echo "MLFLOW_TRACKING_URI=sqlite:///mlflow.db" >> $GITHUB_ENV

      - name: Run MLflow Project
        run: mlflow run MLProject -e main --env-manager local --experiment-name Telco_Churn_RF

      - name: Upload MLflow Results
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-runs
          path: mlflow.db

      - name: Complete job
        run: echo "Job completed successfully"
