name: ML Workflow CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.12
          environment-file: MLProject/conda.yaml
          activate-environment: ml-env
          use-mamba: true

      - name: Verify Environment
        run: |
          conda info
          conda list

      - name: Install extra dependencies via pip
        run: |
          pip install --upgrade pip
          pip install mlflow dagshub tqdm

      - name: Run Modelling Script
        run: |
          mkdir -p MLProject/output
          python MLProject/modelling.py

      - name: Upload Modelling Output
        uses: actions/upload-artifact@v3
        with:
          name: modelling-results
          path: MLProject/output/
